# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [21]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [5]:
u1 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv'
u2 = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv'
c1 = pd.read_csv(u1)
c2 = pd.read_csv(u2)
print(c1.head())
print(c2.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN
1       1          buick skylark 320         NaN          NaN          NaN
2       1         plymouth satellite         NaN          NaN          NaN
3       1              amc rebel sst         NaN          NaN          NaN
4       1                ford torino         NaN          NaN          NaN

   Unnamed: 12  Unnamed: 13
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76
1  20.0          6           225        100    3651          17.7     76
2  18.0          6           250         78    3574          21.0     76
3  18.5          6           250        110    3645          16.2     76
4  17.5          6           258         95    3193          17.8     76

   origin                 car
0       3         honda civic
1       1      dodge aspen se
2       1   ford granada ghia
3       1  pontiac ventura sj
4       1       amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [9]:
c1 = c1.loc[:, 'mpg':'car']
c1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [10]:
print(c1.shape[0])
c2.shape[0]

198

200

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [20]:
c = pd.concat([c1, c2], ignore_index=True)
c

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120,79,2625,18.6,82,1,ford ranger
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [29]:
ro = np.random.randint(15000, 73001, size=c.shape[0], dtype='int64')
ro

array([31898, 70658, 29664, 72058, 41203, 68445, 69764, 63694, 21405,
       52172, 50132, 25305, 56465, 16252, 60011, 30067, 35589, 16669,
       59666, 71619, 61555, 55627, 15294, 15609, 56792, 25426, 28125,
       41193, 46419, 45028, 38388, 55554, 40598, 50601, 31682, 68846,
       50550, 31071, 37833, 41278, 35502, 33468, 31373, 59067, 15888,
       64366, 58514, 48547, 44509, 37620, 44130, 57805, 66595, 40046,
       49432, 66349, 45826, 62206, 56053, 23541, 31106, 51191, 72914,
       34103, 63699, 68675, 62055, 32189, 53528, 53926, 51089, 70293,
       58463, 24178, 35270, 44904, 24464, 50547, 41349, 71969, 16744,
       22398, 58683, 68578, 48343, 62634, 70777, 31863, 46355, 34025,
       52427, 34933, 38379, 19671, 23394, 59170, 40108, 70084, 54750,
       27374, 56012, 28668, 37136, 56161, 20294, 64774, 51857, 65974,
       67987, 68461, 38603, 54005, 45446, 16209, 31698, 66150, 21774,
       46749, 68039, 31470, 32317, 34512, 29370, 28666, 70777, 36989,
       28070, 43839, 51689, 16300, 70791, 55217, 22174, 54429, 46781,
       66411, 72604, 33481, 52753, 44487, 25856, 34919, 71291, 41848,
       60558, 53642, 33195, 57581, 31787, 22341, 66642, 33234, 22686,
       19414, 25495, 67258, 72735, 70888, 49040, 57439, 69818, 33171,
       34546, 38672, 15370, 61046, 51980, 25459, 55354, 39584, 67796,
       53499, 35926, 35086, 36673, 38116, 29090, 68216, 50600, 26006,
       29881, 34540, 43537, 61762, 54705, 64883, 37202, 30280, 33990,
       41108, 37177, 23358, 72226, 66992, 26308, 47029, 51180, 40192,
       41793, 19168, 43989, 62306, 56254, 35862, 25963, 72677, 38866,
       41485, 66081, 33727, 26413, 39331, 27836, 29495, 45610, 55024,
       59171, 53941, 72184, 25958, 67734, 52311, 45702, 44258, 69335,
       20431, 53977, 49252, 72748, 51304, 68862, 69065, 49914, 62084,
       34034, 55850, 51632, 24200, 29171, 70102, 34796, 38212, 59245,
       30722, 52616, 21478, 37400, 18644, 30544, 66164, 32509, 16568,
       17265, 27206, 39657, 69909, 18635, 20200, 31193, 61137, 56729,
       41420, 49857, 52145, 21988, 44568, 40018, 57223, 38698, 65275,
       38391, 48690, 29157, 71402, 35207, 37915, 19572, 20739, 33267,
       61333, 32709, 22120, 24179, 22714, 46100, 35895, 16875, 38389,
       62449, 36845, 45169, 16197, 67583, 26933, 54096, 25651, 15386,
       70833, 35357, 34573, 33788, 69803, 34616, 55148, 53589, 48135,
       72717, 71633, 19117, 68001, 30543, 23214, 60153, 40717, 49070,
       22496, 69152, 52055, 62990, 44490, 57035, 66142, 22447, 59103,
       20122, 30539, 61457, 72774, 47954, 45660, 58101, 44894, 22508,
       42025, 41399, 64246, 24651, 42312, 58374, 27227, 56939, 32455,
       50396, 28975, 22764, 29987, 17029, 22886, 38177, 58743, 26796,
       37548, 31380, 18838, 15639, 22287, 48231, 16031, 50501, 35513,
       57555, 42024, 17565, 15992, 24167, 50286, 21571, 63807, 70288,
       41077, 18077, 21118, 71553, 52298, 52504, 22796, 56301, 32010,
       32256, 67712, 39608, 57963, 20564, 47480, 69960, 32452, 16880,
       45578, 44528, 36063, 30287, 44245, 72196, 48658, 70278, 17926,
       64152, 60330])

### Step 8. Add the column owners to cars

In [30]:
c['owners'] = ro
c

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,31898
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,70658
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,29664
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,72058
4,17.0,8,302,140,3449,10.5,70,1,ford torino,41203
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,48658
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,70278
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage,17926
396,28.0,4,120,79,2625,18.6,82,1,ford ranger,64152
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10,60330